apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmdb-hostserver
  labels:
    app: cmdb-hostserver
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cmdb-hostserver
    spec:
      nodeSelector:
        kubernetes.io/role: node
      containers:
      - name: cmdb-hostserver
        image: cmdb-hostserver:3.1.0
        env:
        - name: ZOOKEEPER_PATH
          value: 192.168.132.139:2181
        ports:
        - containerPort: 60001

---

kind: Service
apiVersion: v1
metadata:
  name: cmdb-hostserver
  labels:
    app: cmdb-hostserver
  namespace: default
spec:
  selector:
    app: cmdb-hostserver
  ports:
  - name: cmdb-hostserver
    targetPort: 60001
    port: 60001
    protocol: TCP