apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmdb-toposerver
  labels:
    app: cmdb-toposerver
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cmdb-toposerver
    spec:
      nodeSelector:
        kubernetes.io/role: node
      containers:
      - name: cmdb-toposerver
        image: cmdb-toposerver:3.1.0
        env:
        - name: ZOOKEEPER_PATH
          value: 192.168.132.139:2181
        ports:
        - containerPort: 60002

---

kind: Service
apiVersion: v1
metadata:
  name: cmdb-toposerver
  labels:
    app: cmdb-toposerver
  namespace: default
spec:
  selector:
    app: cmdb-toposerver
  ports:
  - name: cmdb-toposerver
    targetPort: 60002
    port: 60002
    protocol: TCP